### PR TITLE
Update Azure Storage SDK to v12

### PR DESCRIPTION
**Pull request by cdekkerpossibilit**
Updated the BlobOptimisticDataStore class and dependent tests to Azure.Storage.Blobs Versio 12.8.1

### CODE REVIEW

**Comment by hossambarakat** [comment]
The package [Microsoft.Azure.Storage.Blob](https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/) has been deprecated and the suggested alternative is [Azure.Storage.Blobs](https://www.nuget.org/packages/Azure.Storage.Blobs) which is already used in this project. Could you help me understand the reason behind using `Microsoft.Azure.Storage.Blob`?
image

**Comment by cdekkerpossibilit** [comment]
> The package [Microsoft.Azure.Storage.Blob](https://www.nuget.org/packages/Microsoft.Azure.Storage.Blob/) has been deprecated and the suggested alternative is [Azure.Storage.Blobs](https://www.nuget.org/packages/Azure.Storage.Blobs) which is already used in this project. Could you help me understand the reason behind using `Microsoft.Azure.Storage.Blob`?
> image

It isn't though, the change uses:

image

**Comment by gplwhite** [comment]
@hossambarakat Could you take another look at this pull request. I think you were wrong in your comment about which version of the Azure Storage client libraries are used currently vs in this pull request. This pull request is trying to move SnowMaker to the newer Azure.Storage.Blobs library.
It would be great to have SnowMaker not dependent on a deprecated library like it is currently.

**Comment by hossambarakat** [comment]
Hi @cdekkerpossibilit @gplwhite, Thanks for your patience. I had another look and you are right the `Azure.Storage.Blobs` is the new client library. I mixed the names of the packages when I was reviewing the pull request.

Great work on the upgrade, I have added a couple of small comments. I'd be happy to the PR once you address them.

**Comment by cdekkerpossibilit** [comment]
> Hi @cdekkerpossibilit @gplwhite, Thanks for your patience. I had another look and you are right the `Azure.Storage.Blobs` is the new client library. I mixed the names of the packages when I was reviewing the pull request.
> 
> Great work on the upgrade, I have added a couple of small comments. I'd be happy to the PR once you address them.

I'll have a look next week

**Comment by cdekkerpossibilit** [comment]
> Hi @cdekkerpossibilit @gplwhite, Thanks for your patience. I had another look and you are right the `Azure.Storage.Blobs` is the new client library. I mixed the names of the packages when I was reviewing the pull request.
> 
> Great work on the upgrade, I have added a couple of small comments. I'd be happy to the PR once you address them.

I must be an idiot or it's because it's friday night nut where do I find the comments you added?

**Comment by hossambarakat** [comment]
@cdekkerpossibilit Check them in this link https://github.com/tathamoddie/SnowMaker/pull/10/files

**Comment by cdekkerpossibilit** [comment]
For unit testing in the pipeline you can use azurite, I use it in Azure DevOps by just running npm install

sudo npm install -g azurite
sudo mkdir azurite
sudo azurite --silent --location azurite --debug azurite\debug.log &

**Comment by cdekkerpossibilit** [comment]
Also, @hossambarakat  .NET Core 2.1 is out of support. I remove it from the target frameworks.

**Comment by hossambarakat** [comment]
> For unit testing in the pipeline you can use azurite, I use it in Azure DevOps by just running npm install
> 
> sudo npm install -g azurite sudo mkdir azurite sudo azurite --silent --location azurite --debug azurite\debug.log &



> For unit testing in the pipeline you can use azurite, I use it in Azure DevOps by just running npm install
> 
> sudo npm install -g azurite sudo mkdir azurite sudo azurite --silent --location azurite --debug azurite\debug.log &

Yup, I usually use Azurite for local testing. I am planning to run the integration tests on CI using Azurite.

**Comment by hossambarakat** [comment]
@cdekkerpossibilit I have published a new version of the package available [here](https://www.nuget.org/packages/SnowMaker/3.0.0)

**Pull request merged**
